development:
  adapter: mysql
  database: rearview_dummy_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: rearview_dummy_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: rearview_dummy_production
  username: root
  password:
  host: localhost
